# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8000/message/1/
Accept: application/json
Cache-Control: no-cache

###

POST http://localhost:8000/message/1
Content-Type: application/json
Accept: application/json

{
    "id": "1",
    "contents": "hello"
}

###

GET http://localhost:8000/face/1
Content-Type: application/json
Accept: application/json

###
POST http://localhost:8000/face/1
Content-Type: application/json
Accept: application/json

{
  "AU_c": {
    "AU01": 1.0,
    "AU02": 0.0,
    "AU04": 0.0,
    "AU05": 1.0,
    "AU06": 0.0,
    "AU07": 0.0,
    "AU09": 0.0,
    "AU10": 0.0,
    "AU12": 0.0,
    "AU14": 0.0,
    "AU15": 0.0,
    "AU17": 0.0,
    "AU20": 0.0,
    "AU23": 0.0,
    "AU25": 1.0,
    "AU26": 0.0,
    "AU28": 0.0,
    "AU45": 0.0
  },
  "AU_r": {
    "AU01": 1.8714948447237636,
    "AU02": 0.14530619743745432,
    "AU04": 1.6321265838127277,
    "AU05": 0.5689271391348898,
    "AU06": 0.5805223228929635,
    "AU07": 0.11928368194415362,
    "AU09": 0.0,
    "AU10": 0.5195018480307121,
    "AU12": 0.9630527828123969,
    "AU14": 1.8647234641146695,
    "AU15": 0.9190950562249298,
    "AU17": 0.0,
    "AU20": 0.3590910490572159,
    "AU23": 0.0,
    "AU25": 4.747228264050687,
    "AU26": 0.5775396768437795,
    "AU45": 0.5265650522017075
  },
  "face_id": 45,
  "frame_num": 45,
  "gazeDirection0": {
    "x": 0.041743289679288864,
    "y": -0.018191881477832794,
    "z": -0.9989627599716187
  },
  "gazeDirection1": {
    "x": 0.002705889753997326,
    "y": 0.008696231059730053,
    "z": -0.9999585151672363
  },
  "gaze_angle": {
    "x": 0.022232919931411743,
    "y": -0.004750351421535015
  },
  "landmark_confidence": 0.875,
  "landmark_detection_success": true,
  "pose_estimate": {
    "Rx": -0.0813940167427063,
    "Ry": 0.01696261577308178,
    "Rz": 0.08898824453353882,
    "Tx": 6.722573280334473,
    "Ty": 134.85861206054688,
    "Tz": 351.3978576660156
  },
  "time_stamp": 5.206921278
}

###

GET http://localhost:8000/api/email?from_name=max&access_token=bob&personality=neurotic
Content-Type: application/json
Accept: application/json

###
GET http://localhost:8000/api/essay/bob
Content-Type: application/json
Accept: application/json

###
